--- # local 설정
spring:
  config:
    activate:
      on-profile: "unipass-test"

unipass_url : https://tunipass.customs.go.kr:38010/

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "unipass-dev"

unipass_url : https://tunipass.customs.go.kr:38010/

--- # prod 설정
spring:
  config:
    activate:
      on-profile: "unipass-prod"

unipass_url : https://unipass.customs.go.kr:38010/