greeting:
  message: this is PROD application.yml
  
unipass_url : https://unipass.customs.go.kr:38010/

retrieve_iopr_rprt_brkd:
  license_key: l290u203i049c292n040c080k0
  service_url: ext/rest/ioprRprtQry/retrieveIoprRprtBrkd
